Implement default values
lost-illusi0n/lostorm pull request #10
Opened 2020-10-07 19:33 UTC by DeMack

Addresses #3

2020-10-07 19:51 UTC, lost-illusi0n requested changes
Don't forget to add the default value implementation to the schema generator.
Other than that, everything looks fine!

2020-10-07 19:51 UTC, lost-illusi0n commented on annotation-processor/src/main/kotlin/net/lostillusion/lostorm/annotationprocessor/AnnotationProcessor.kt
> +const val JVM_TYPE = "jvmType"
Even though this module won't be public to the user, it's probably better to stick with the documentation and have this ``const val CUSTOM_TYPE = "customType``
as there probably won't ever even be a JVM implementation of something in the context of this processor.

2020-10-07 19:51 UTC, lost-illusi0n commented on annotation-processor/src/main/kotlin/net/lostillusion/lostorm/annotationprocessor/Renderers.kt
> +    private val jvmType: TypeName,
``customType`` here as well

2020-10-07 19:51 UTC, lost-illusi0n commented on annotation-processor/src/main/kotlin/net/lostillusion/lostorm/annotationprocessor/AnnotationProcessor.kt
> +        mapOf(Pair(JVM_TYPE, type), Pair(SQL_TYPE, type))
``customType`` here as well

2020-10-07 19:51 UTC, lost-illusi0n commented on annotation-processor/src/main/kotlin/net/lostillusion/lostorm/annotationprocessor/AnnotationProcessor.kt
> +            put(JVM_TYPE, ClassName.bestGuess(typeArgs[0]))
``customType`` here as well

2020-10-07 19:51 UTC, lost-illusi0n commented on annotation-processor/src/main/kotlin/net/lostillusion/lostorm/annotationprocessor/AnnotationProcessor.kt
> +                        typeArguments.getValue(JVM_TYPE),
``customType`` here as well

2020-10-07 19:51 UTC, lost-illusi0n commented on annotations/src/main/kotlin/net/lostillusion/lostorm/annotations/Columns.kt
> +    val defaultValue: String = ""
This should be ``¯\\_(ツ)_/¯`` as we don't want to automatically give things default values.

2020-10-07 20:31 UTC, DeMack commented on annotations/src/main/kotlin/net/lostillusion/lostorm/annotations/Columns.kt
> +    val defaultValue: String = ""
Ah, good catch.

2020-10-07 20:38 UTC, DeMack commented on annotation-processor/src/main/kotlin/net/lostillusion/lostorm/annotationprocessor/AnnotationProcessor.kt
> +const val JVM_TYPE = "jvmType"
Everything is a JVM implementation,though. That's where the bytecode runs, and the plugin is the jvm flavor.

2020-10-07 20:44 UTC, DeMack commented
> Don't forget to add the default value implementation to the schema generator.
> Other than that, everything looks fine!

Is that not what happens [here](https://github.com/lost-illusi0n/lostorm/blob/317cd52b21784e57a7a805bb69bc9ca694aadd0e/mapper/src/main/kotlin/net/lostillusion/lostorm/mapper/SchemaUtils.kt#L19)?

2020-10-07 21:02 UTC, lost-illusi0n commented on annotation-processor/src/main/kotlin/net/lostillusion/lostorm/annotationprocessor/AnnotationProcessor.kt
> +const val JVM_TYPE = "jvmType"
In the context of the processor it is not. We want the kotlin type, we dont want`` java.lang.String``, we want ``kotlin.String``.

2020-10-07 21:05 UTC, lost-illusi0n commented
Yes, however since we convert it to a SQL-safe string during annotation processing, there is no need for the ``toSafeSQL`` call. Along with this you'll probably want to replace [the type of T](https://github.com/lost-illusi0n/lostorm/blob/317cd52b21784e57a7a805bb69bc9ca694aadd0e/mapper/src/main/kotlin/net/lostillusion/lostorm/mapper/Column.kt#L9) with a String as its already formatted in the processor.

2020-10-07 21:13 UTC, DeMack commented
Ah, OK I see what you mean. I'll get that.

2020-10-07 21:17 UTC, DeMack commented on annotation-processor/src/main/kotlin/net/lostillusion/lostorm/annotationprocessor/AnnotationProcessor.kt
> +const val JVM_TYPE = "jvmType"
Kotlin is designed to be interoperable with Java, so the assumption when using a Kotlin lib is that it should work with Java classes as well. This means that we can't _really_ guarantee that what is provided here will be exclusively Kotlin. Actually having said that, would this work with on a Java POJO?

2020-10-07 21:53 UTC, lost-illusi0n commented on annotation-processor/src/main/kotlin/net/lostillusion/lostorm/annotationprocessor/AnnotationProcessor.kt
> +const val JVM_TYPE = "jvmType"
This library is not compatible with Java currently. That would be another PR to let it have java support. But that's beside the point. It's still the user's custom type, whether java or kotlin.

2020-10-08 01:28 UTC, DeMack commented on annotation-processor/src/main/kotlin/net/lostillusion/lostorm/annotationprocessor/AnnotationProcessor.kt
> +const val JVM_TYPE = "jvmType"
OK. That makes sense. I can get that. Side note, though, since this isn't currently exactly widely used, it's not really an issue, but we may want to make note that this isn't currently compatible with Java in the `README.md`. That aside, what about `ENTITY_TYPE`?

2020-10-08 03:04 UTC, lost-illusi0n commented on annotation-processor/src/main/kotlin/net/lostillusion/lostorm/annotationprocessor/AnnotationProcessor.kt
> +const val JVM_TYPE = "jvmType"
I suppose we could, though Kotlin ORMs aren't exactly known for having the interop with Java due to its excessive use of Kotlin language specific features. I'll add it in future. Anyways, ``ENTITY_TYPE`` also seems incorrect. This argument will always be the property type. Whether that be a some data class which would require a Converter, or an already supported data type. This completely depends on the user. Is there any reason why you don't think ``CUSTOM_TYPE`` would fit?

2020-10-12 20:06 UTC, lost-illusi0n commented
Hey, it's been almost a week since the last update. Do you need help with anything?

2020-10-12 20:12 UTC, DeMack commented
Sorry, got busy last week, but I've got more time this week. I should be
able to finish this up tonight or tomorrow.

On Mon, Oct 12, 2020, 4:07 PM lost-illusi0n <notifications@github.com>
wrote:

> Hey, it's been almost a week since the last update. Do you need help with
> anything?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lost-illusi0n/lostorm/pull/10#issuecomment-707320733>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF3BTLRRA4MQWLXIRFQDRP3SKNOW7ANCNFSM4SH2DUGQ>
> .
>

2020-10-12 20:14 UTC, lost-illusi0n commented
Sounds good! 😄

2020-10-14 15:11 UTC, DeMack commented on annotation-processor/src/main/kotlin/net/lostillusion/lostorm/annotationprocessor/AnnotationProcessor.kt
> +const val JVM_TYPE = "jvmType"
Not strictly, I was just searching for something more explicit as to what `CUSTOM` means, but I can go with that.

2020-10-15 04:57 UTC, lost-illusi0n reviewed
Looks good to me, I'll test it out later today. If you could, would you be able to squash these commits into one as to not pollute the history.

2020-10-15 04:58 UTC, DeMack commented
Can do.

2020-10-15 14:11 UTC, lost-illusi0n commented
Seems like it works to me. I'll follow this up with a commit to allow for inserting pieces of data instead of the whole data class. 👍

2020-10-15 14:11 UTC, lost-illusi0n approved these changes

2020-10-15 14:12 UTC, lost-illusi0n commented
Oh and if you could just squash this into one commit and force push 😅

2020-10-15 14:22 UTC, DeMack commented
Squashed. This should be good to merge.

2020-10-15 14:48 UTC, merged